### ISSUE TITLE
масштаб 100%

### ISSUE THREAD

**Issue by dasmike** [kostya-gil/test-1#1]
при масштабе 100%, при ширине 1280 пикселей резюме выглядит вот так
![image](https://cloud.githubusercontent.com/assets/9625184/18229839/583af818-72b1-11e6-98eb-2c8932ea9900.png)
желательно переходить в формат одной колонки при 600 пикселях и ниже

**Comment by kostya-gil** [comment]
Получилось где то около 850px переход в 1 колонку и то сжал наверно максимум, смотрится так себе.
