### ISSUE TITLE
Горизонтальные полоски в названиях блоков

### ISSUE THREAD

**Issue by Znack** [kostya-gil/test-1#3]
У всех всегда траблы с этим элементом, у тебя тоже самое проявилось :)
Полоска должна выравниваться по вертикали динамически (top 50% никуда не годится). И полоска должна обладать динамической длиной, то есть для каждой отдельной полоски писать width: 38.5%; или 34.5%; тоже не надо.
Решений у этой проблемы несколько, выбирай на свой вкус с объяснением сюда в комментарий почему именно так решил делать

**Comment by kostya-gil** [comment]
Полоска должна подстраиваться под ширину родителя или как? Потому, что это скорее визуальное оформление, не думаю, что для него через js что-то делают. А в макете у всех разные длины полосок.

**Comment by Znack** [comment]
Да, там видимая часть полоски (то есть никто не запрещает часть полоски скрывать просто) должна зависеть от ширины заголовка слева и от ширины родителя
