### ISSUE TITLE
Немастабируемый и неочевидный способ создания рейтинга скиллов

### ISSUE THREAD

**Issue by Znack** [kostya-gil/test-1#5]
У тебя захардкожены значения скиллов в спрайте, по идее тут вообще картинки, тем более спрайты не нужны :)

**Comment by kostya-gil** [comment]
Мне инлайном вставить картинки? Или придумтать кликабельную рейт систему?

**Comment by Znack** [comment]
Да сделай это отдельными блоками и просто через `background-color` и `border-radius` сделай

**Comment by kostya-gil** [comment]
Сделал, как и описано, но хоть убей в PixelPerfect не могу подогнать, первые несколько кругляшков совпадают, потом едет.

**Comment by kostya-gil** [comment]
И на счет полосок посередине, у последних 2ух заголовков, отступ от текста больше(опять же почему? задумка дизайнера?) и поэтому не совпадает. Их править?

**Comment by kostya-gil** [comment]
Не выдержал и подровнял линии:)
