### ISSUE TITLE
В мобильной верстке колонки поехали

### ISSUE THREAD

**Issue by Znack** [kostya-gil/test-1#8]
Открыли в эмуляторе айпада - колонки 2 и 3 почему-то на одной горизонтали
![image](https://cloud.githubusercontent.com/assets/2928964/18230350/cde20392-72d2-11e6-86db-38050f4dc374.png)

**Comment by kostya-gil** [comment]
Колонки сделать чтобы были отцентрированы между собой?  Или сместить вниз?

**Comment by Znack** [comment]
Сместить вниз, чтобы одна под другой

**Comment by kostya-gil** [comment]
Поправил. По поводу версий планшетов и т.д. Я максимально пытался сохранить состояние двух колонок, но контент сужался и последние колонки не на равных стоят. Можно отровнять их, но слишком частые медиа будут, плюс ко всему контент может быть разный. Макет изначально сделан по мне не очень)), либо должны для всех разрешений его состояния быть, чтобы сразу видеть общую картину и писать css, думаю заранее о возможных ньюансах. Так что сильно не стал, заморачиваться.
